// <auto-generated />
using System;
using LocalVibe.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalVibe.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LocalVibe.API.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("LocalVibe.API.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalImages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DownvotesCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("UpvotesCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 5, 27, 8, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Quán nhỏ nằm trong nhà ở phố Lê Ngọc Hân, bán món bánh đúc gia truyền lâu năm cùng bún, miến, bánh đa. Không gian đơn giản nhưng luôn đông khách ăn tại chỗ. — Hà Nội",
                            DownvotesCount = 0,
                            Latitude = 21.0166,
                            Longitude = 105.854,
                            Score = 0,
                            Tag = "Food",
                            Title = "Bánh đúc nóng Lê Ngọc Hân",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 2,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 5, 28, 9, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Quán phở không biển hiệu, không bàn ghế, khách phải tự bưng bát ra ngồi vỉa hè ăn. Mở từ chiều, nước dùng đậm đà, là một trong những quán phở 'ẩn' đặc trưng của phố cổ. — Hà Nội",
                            DownvotesCount = 0,
                            Latitude = 21.028500000000001,
                            Longitude = 105.84999999999999,
                            Score = 0,
                            Tag = "Food",
                            Title = "Phở \"bưng\" Hàng Trống",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 3,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 5, 28, 14, 20, 0, 0, DateTimeKind.Utc),
                            Description = "Gánh hàng nhỏ bán sứa đỏ chấm mắm tôm tồn tại hơn 80 năm, chế biến trong ngõ rồi mang ra bán. Món ăn vặt đặc trưng mùa hè của người Hà Nội. — Hà Nội",
                            DownvotesCount = 0,
                            Latitude = 21.034500000000001,
                            Longitude = 105.8505,
                            Score = 0,
                            Tag = "Food",
                            Title = "Sứa đỏ mắm tôm Hàng Chiếu",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 4,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 5, 29, 7, 45, 0, 0, DateTimeKind.Utc),
                            Description = "Gánh bún ốc cổ truyền ngồi vỉa hè phố Lương Ngọc Quyến, chỉ đơn giản bún, ốc, cà chua, hành lá và nước dùng chua dịu từ dấm bỗng. — Hà Nội",
                            DownvotesCount = 0,
                            Latitude = 21.030999999999999,
                            Longitude = 105.852,
                            Score = 0,
                            Tag = "Food",
                            Title = "Bún ốc Cô Giang",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 5,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 5, 30, 11, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Quán nằm sâu trong hẻm ẩm thực Phan Văn Hân, chuyên món bò cuốn lá lốt nướng than thơm nồng ngay từ đầu hẻm. Giá bình dân, chủ yếu khách quen địa phương. — TP. Hồ Chí Minh",
                            DownvotesCount = 0,
                            Latitude = 10.803000000000001,
                            Longitude = 106.709,
                            Score = 0,
                            Tag = "Food",
                            Title = "Bò lá lốt hẻm Phan Văn Hân",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 6,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 5, 31, 8, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Tiệm bánh mì chảo lâu đời hơn nửa thế kỷ, nằm khiêm tốn trong hẻm nhỏ nhưng luôn đông khách buổi sáng. Phần ăn đầy đặn với trứng, chả, pate, xúc xích. — TP. Hồ Chí Minh",
                            DownvotesCount = 0,
                            Latitude = 10.782,
                            Longitude = 106.69,
                            Score = 0,
                            Tag = "Food",
                            Title = "Bánh mì chảo Hòa Mã",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 7,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 1, 10, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Một trong những địa chỉ cơm tấm sườn bì chả được người Sài Gòn lâu năm tin chọn, nước mắm pha theo công thức riêng. — TP. Hồ Chí Minh",
                            DownvotesCount = 0,
                            Latitude = 10.798999999999999,
                            Longitude = 106.68000000000001,
                            Score = 0,
                            Tag = "Food",
                            Title = "Cơm tấm Ba Ghiền",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 8,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 1, 18, 40, 0, 0, DateTimeKind.Utc),
                            Description = "Văn hóa ăn khuya đặc trưng của Sài Gòn: xe hủ tiếu nhỏ đẩy dọc hẻm phố, báo hiệu bằng tiếng gõ thanh gỗ thay cho rao hàng. — TP. Hồ Chí Minh",
                            DownvotesCount = 0,
                            Latitude = 10.766999999999999,
                            Longitude = 106.69199999999999,
                            Score = 0,
                            Tag = "Food",
                            Title = "Hủ tiếu gõ đêm Sài Gòn",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 9,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 2, 7, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Gánh bún bò gia truyền hơn 70 năm trên đường Bạch Đằng, chỉ bán buổi sáng và thường hết hàng trước 10 giờ. Đặc biệt là không có thịt bò mà thay bằng chả cua, huyết, ba chỉ. — Huế",
                            DownvotesCount = 0,
                            Latitude = 16.467400000000001,
                            Longitude = 107.59050000000001,
                            Score = 0,
                            Tag = "Food",
                            Title = "Bún bò Mệ Kéo",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 10,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 3, 9, 20, 0, 0, DateTimeKind.Utc),
                            Description = "Quán bánh lâu năm phục vụ trọn bộ đặc sản bánh Huế: bánh bèo, bánh nậm, bánh lọc, mỗi loại mang hương vị riêng nhưng đều đậm chất cố đô. — Huế",
                            DownvotesCount = 0,
                            Latitude = 16.460999999999999,
                            Longitude = 107.587,
                            Score = 0,
                            Tag = "Food",
                            Title = "Bánh bèo, nậm, lọc Bà Đỏ",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 11,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 3, 15, 10, 0, 0, DateTimeKind.Utc),
                            Description = "Món cơm hến trộn dân dã của Huế, nguyên liệu hến tươi lấy ngay từ Cồn Hến giữa sông Hương, ăn cùng nước hến nóng và mắm ruốc. — Huế",
                            DownvotesCount = 0,
                            Latitude = 16.472999999999999,
                            Longitude = 107.605,
                            Score = 0,
                            Tag = "Food",
                            Title = "Cơm hến Cồn Hến",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 12,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 4, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Món cao lầu trứ danh phố Hội, theo cách làm truyền thống dùng nước từ giếng cổ Bá Lễ để tạo độ dai đặc trưng cho sợi mì. — Hội An",
                            DownvotesCount = 0,
                            Latitude = 15.880100000000001,
                            Longitude = 108.33799999999999,
                            Score = 0,
                            Tag = "Food",
                            Title = "Cao lầu giếng Bá Lễ",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 13,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 5, 6, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Ăn bún riêu ngay trên thuyền giữa chợ nổi Cái Răng vào sáng sớm, vừa thưởng thức món ăn vừa ngắm cảnh ghe thuyền tấp nập. — Cần Thơ",
                            DownvotesCount = 0,
                            Latitude = 10.005000000000001,
                            Longitude = 105.747,
                            Score = 0,
                            Tag = "Food",
                            Title = "Bún riêu chợ nổi Cái Răng",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 14,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 5, 14, 45, 0, 0, DateTimeKind.Utc),
                            Description = "Món hủ tiếu chiên giòn phủ trứng, thịt khìa và đậu phộng, được dân địa phương gọi vui là 'pizza' kiểu miền Tây, bán gần lò hủ tiếu truyền thống. — Cần Thơ",
                            DownvotesCount = 0,
                            Latitude = 10.007999999999999,
                            Longitude = 105.749,
                            Score = 0,
                            Tag = "Food",
                            Title = "Pizza hủ tiếu lò Sáu Hoài",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 15,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Khu hẻm tập trung nhiều quán lẩu vịt nấu chao lâu năm, vị béo đặc trưng của chao kết hợp thịt vịt mềm, ăn cùng rau và bún. — Cần Thơ",
                            DownvotesCount = 0,
                            Latitude = 10.031000000000001,
                            Longitude = 105.774,
                            Score = 0,
                            Tag = "Food",
                            Title = "Lẩu vịt nấu chao hẻm Lý Tự Trọng",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 16,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 7, 8, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Quán cà phê phố núi phục vụ cả ngày, nổi tiếng với hai món đặc sản Đà Lạt: bánh ướt lòng gà thơm và bánh căn nóng giòn. — Đà Lạt",
                            DownvotesCount = 0,
                            Latitude = 11.952,
                            Longitude = 108.435,
                            Score = 0,
                            Tag = "Food",
                            Title = "Bánh ướt lòng gà & bánh căn Bình Minh Ơi",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 17,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 8, 10, 20, 0, 0, DateTimeKind.Utc),
                            Description = "Quán cà phê sách nằm trong ngõ nhỏ giữa phố cổ, không gian châu Âu hoài cổ, lý tưởng để đọc sách và làm việc yên tĩnh. — Hà Nội",
                            DownvotesCount = 0,
                            Latitude = 21.032,
                            Longitude = 105.84999999999999,
                            Score = 0,
                            Tag = "Coffee",
                            Title = "Tranquil Books & Coffee",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 18,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 9, 7, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Quán cà phê ẩn trong khu tập thể cũ trên phố Hồng Hà, phải leo cầu thang hẹp mới lên được. Ban công xanh mát nhìn xuống phố nhưng vẫn giữ được sự yên tĩnh hiếm có. — Hà Nội",
                            DownvotesCount = 0,
                            Latitude = 21.042000000000002,
                            Longitude = 105.855,
                            Score = 0,
                            Tag = "Coffee",
                            Title = "Aerie Coffee",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 19,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 9, 20, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Quán cà phê sách nằm trong khu tập thể cũ ở phố Bà Triệu, có sân thượng thoáng và hay tổ chức giao lưu sách, phim. — Hà Nội",
                            DownvotesCount = 0,
                            Latitude = 21.0167,
                            Longitude = 105.85080000000001,
                            Score = 0,
                            Tag = "Coffee",
                            Title = "Tổ Chim Xanh",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 20,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Quán cà phê phong cách Pháp cổ nằm trong ngõ nhỏ, mở 24/24, nội thất sofa êm ái và kệ sách phong phú. — Hà Nội",
                            DownvotesCount = 0,
                            Latitude = 21.0245,
                            Longitude = 105.858,
                            Score = 0,
                            Tag = "Coffee",
                            Title = "Xofa Cafe & Bistro",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 21,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 11, 8, 45, 0, 0, DateTimeKind.Utc),
                            Description = "Quán cà phê vườn nằm sâu trong hẻm yên tĩnh, thiết kế từ gỗ lũa mộc mạc, không gian xanh mát tách biệt khỏi phố cổ ồn ào. — Hội An",
                            DownvotesCount = 0,
                            Latitude = 15.878,
                            Longitude = 108.32599999999999,
                            Score = 0,
                            Tag = "Coffee",
                            Title = "Hoi An Coffee Hub",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 22,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 12, 10, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Quán trà do nhân viên khiếm thính phục vụ, không gian tĩnh lặng tuyệt đối, khách được khuyến khích giao tiếp bằng giấy bút hoặc ra dấu. — Hội An",
                            DownvotesCount = 0,
                            Latitude = 15.8794,
                            Longitude = 108.32599999999999,
                            Score = 0,
                            Tag = "Coffee",
                            Title = "Reaching Out Teahouse",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 23,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 12, 15, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Quán cà phê đồng quê giữa cánh đồng lúa Cẩm Hà, không gian mở bốn bề ruộng xanh, cách xa sự ồn ào của trung tâm phố cổ. — Hội An",
                            DownvotesCount = 0,
                            Latitude = 15.901999999999999,
                            Longitude = 108.315,
                            Score = 0,
                            Tag = "Coffee",
                            Title = "Roving Chillhouse",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 24,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 13, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Quán cà phê kết hợp nhà hàng và homestay gần núi Langbiang, nổi bật với vườn hoa và view nhìn thẳng ra đỉnh Hòn Bồ. — Đà Lạt",
                            DownvotesCount = 0,
                            Latitude = 11.946,
                            Longitude = 108.44199999999999,
                            Score = 0,
                            Tag = "Coffee",
                            Title = "Túi Mơ To",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 25,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 14, 9, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Quán cà phê nằm giữa đồi chè và vườn cà phê chồn, tầm nhìn 360 độ ra cao nguyên, nổi tiếng với cà phê chồn nguyên chất. — Đà Lạt",
                            DownvotesCount = 0,
                            Latitude = 11.91,
                            Longitude = 108.48999999999999,
                            Score = 0,
                            Tag = "Coffee",
                            Title = "Mê Linh Coffee Garden",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 26,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 15, 11, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Quán cà phê lâu đời giữa trung tâm Đà Lạt, giữ nguyên nội thất cổ và nhạc Trịnh, phù hợp cho ai yêu không khí hoài niệm. — Đà Lạt",
                            DownvotesCount = 0,
                            Latitude = 11.9404,
                            Longitude = 108.438,
                            Score = 0,
                            Tag = "Coffee",
                            Title = "Cà Phê Tùng",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 27,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 16, 7, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Cung đường ven biển dài khoảng 21km nối Đà Nẵng và Huế, nổi tiếng với hơn 100 khúc cua và view toàn cảnh vịnh Lăng Cô, bán đảo Sơn Trà. — Đà Nẵng - Huế",
                            DownvotesCount = 0,
                            Latitude = 16.209,
                            Longitude = 108.117,
                            Score = 0,
                            Tag = "ScenicRoute",
                            Title = "Đèo Hải Vân",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 28,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 17, 8, 45, 0, 0, DateTimeKind.Utc),
                            Description = "Một trong tứ đại đỉnh đèo Việt Nam, ôm trọn dòng sông Nho Quế xanh ngọc, đi qua cao nguyên đá Đồng Văn hùng vĩ. — Hà Giang",
                            DownvotesCount = 0,
                            Latitude = 23.274999999999999,
                            Longitude = 105.41,
                            Score = 0,
                            Tag = "ScenicRoute",
                            Title = "Hà Giang Loop - Mã Pí Lèng",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 29,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 18, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cung đường ven biển dài khoảng 250km, đi qua bãi biển Vũng Tàu, hải đăng Kê Gà, và những đồi cát Mũi Né. — Bình Thuận",
                            DownvotesCount = 0,
                            Latitude = 10.933,
                            Longitude = 108.288,
                            Score = 0,
                            Tag = "ScenicRoute",
                            Title = "Sài Gòn - Vũng Tàu - Phan Thiết - Mũi Né",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 30,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 19, 9, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Cung đường phượt khoảng 300km với những khúc cua tay áo lên cao nguyên Lâm Đồng, kết thúc ở thành phố sương mù Đà Lạt. — Lâm Đồng",
                            DownvotesCount = 0,
                            Latitude = 11.547000000000001,
                            Longitude = 107.80500000000001,
                            Score = 0,
                            Tag = "ScenicRoute",
                            Title = "Sài Gòn - Đà Lạt",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 31,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 20, 8, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Cung đường đèo nối thành phố biển và thành phố cao nguyên, đi qua những vách núi hùng vĩ và cánh đồng hoa trên đường lên đèo Khánh Lê. — Khánh Hòa - Lâm Đồng",
                            DownvotesCount = 0,
                            Latitude = 12.050000000000001,
                            Longitude = 108.598,
                            Score = 0,
                            Tag = "ScenicRoute",
                            Title = "Nha Trang - Đà Lạt",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 32,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 21, 10, 45, 0, 0, DateTimeKind.Utc),
                            Description = "Cung đường ven biển từ Ninh Chữ đến Bình Lập, đi qua đồng muối, vườn nho Thái An và vịnh Vĩnh Hy nước trong xanh. — Ninh Thuận - Khánh Hòa",
                            DownvotesCount = 0,
                            Latitude = 11.685,
                            Longitude = 109.148,
                            Score = 0,
                            Tag = "ScenicRoute",
                            Title = "Vịnh Vĩnh Hy - Ninh Chữ - Bình Lập",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 33,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 22, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cung đường ven biển miền Trung đi qua Eo Gió, Kỳ Co và ghềnh đá xếp tầng độc đáo Ghềnh Đá Đĩa. — Bình Định - Phú Yên",
                            DownvotesCount = 0,
                            Latitude = 13.406000000000001,
                            Longitude = 109.246,
                            Score = 0,
                            Tag = "ScenicRoute",
                            Title = "Quy Nhơn - Phú Yên (Ghềnh Đá Đĩa)",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 34,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 23, 8, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Con đèo nối hai tỉnh Phú Yên và Khánh Hòa, một bên là núi xanh, một bên là biển xanh trải dài đến chân trời. — Phú Yên - Khánh Hòa",
                            DownvotesCount = 0,
                            Latitude = 12.933,
                            Longitude = 109.327,
                            Score = 0,
                            Tag = "ScenicRoute",
                            Title = "Đèo Cả",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 35,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 23, 16, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cung đường Tây Bắc đi qua ruộng bậc thang Mù Cang Chải và đèo Pha Đin nổi tiếng, đẹp nhất vào mùa lúa chín tháng 9-10. — Lào Cai - Yên Bái - Điện Biên",
                            DownvotesCount = 0,
                            Latitude = 21.587,
                            Longitude = 103.517,
                            Score = 0,
                            Tag = "ScenicRoute",
                            Title = "Sapa - Mù Cang Chải qua đèo Pha Đin",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 36,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 24, 9, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Cung đường biển khoảng 70km từ Đà Nẵng đến vịnh Lăng Cô, một trong những vịnh biển được đánh giá đẹp nhất Việt Nam. — Đà Nẵng - Thừa Thiên Huế",
                            DownvotesCount = 0,
                            Latitude = 16.239000000000001,
                            Longitude = 108.057,
                            Score = 0,
                            Tag = "ScenicRoute",
                            Title = "Đà Nẵng - Lăng Cô ven biển",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 37,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 25, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cung đường khoảng 250km từ vùng biển cát trắng Bình Thuận lên những con đèo uốn lượn của cao nguyên Lâm Đồng. — Bình Thuận - Lâm Đồng",
                            DownvotesCount = 0,
                            Latitude = 11.523,
                            Longitude = 108.33,
                            Score = 0,
                            Tag = "ScenicRoute",
                            Title = "Phan Thiết - Bình Thuận - Lâm Đồng",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 38,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 25, 14, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Đầm phá được ví như 'vịnh Hạ Long trên cạn' nằm trên cung đường ven biển Huế - Đà Nẵng, nổi bật với cồn cát trắng và rừng nguyên sinh. — Huế",
                            DownvotesCount = 0,
                            Latitude = 16.449999999999999,
                            Longitude = 107.68000000000001,
                            Score = 0,
                            Tag = "ScenicRoute",
                            Title = "Phá Tam Giang",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 39,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DownvotesCount = 0,
                            Latitude = 20.262599999999999,
                            Longitude = 105.8613,
                            Score = 0,
                            Tag = "Hotel",
                            Title = "Homestay Bái Đính Ninh Bình",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 40,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DownvotesCount = 0,
                            Latitude = 16.054400000000001,
                            Longitude = 108.2022,
                            Score = 0,
                            Tag = "Hotel",
                            Title = "Khách sạn Mường Thanh Đà Nẵng",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 41,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DownvotesCount = 0,
                            Latitude = 12.238799999999999,
                            Longitude = 109.19670000000001,
                            Score = 0,
                            Tag = "Hotel",
                            Title = "Resort Ana Mandara Nha Trang",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 42,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DownvotesCount = 0,
                            Latitude = 21.055800000000001,
                            Longitude = 107.76300000000001,
                            Score = 0,
                            Tag = "Hotel",
                            Title = "Homestay Cô Tô Quảng Ninh",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 43,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DownvotesCount = 0,
                            Latitude = 15.880100000000001,
                            Longitude = 108.33799999999999,
                            Score = 0,
                            Tag = "Attraction",
                            Title = "Phố cổ Hội An",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 44,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DownvotesCount = 0,
                            Latitude = 20.9101,
                            Longitude = 107.18389999999999,
                            Score = 0,
                            Tag = "Attraction",
                            Title = "Vịnh Hạ Long",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 45,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DownvotesCount = 0,
                            Latitude = 16.469799999999999,
                            Longitude = 107.5784,
                            Score = 0,
                            Tag = "Attraction",
                            Title = "Hoàng Thành Huế",
                            UpvotesCount = 0
                        },
                        new
                        {
                            Id = 46,
                            AdditionalImages = "[]",
                            CreatedAt = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DownvotesCount = 0,
                            Latitude = 15.7644,
                            Longitude = 108.1169,
                            Score = 0,
                            Tag = "Attraction",
                            Title = "Thánh địa Mỹ Sơn",
                            UpvotesCount = 0
                        });
                });

            modelBuilder.Entity("LocalVibe.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$11$AyFXkt03pFpbJmTpNxVL/O5Gf29bZJHGmr6LzMGb9ZyIns7u4Z2VO",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("LocalVibe.API.Entities.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("VoteType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("VoterToken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PostId", "VoterToken")
                        .IsUnique();

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("LocalVibe.API.Entities.Comment", b =>
                {
                    b.HasOne("LocalVibe.API.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("LocalVibe.API.Entities.Vote", b =>
                {
                    b.HasOne("LocalVibe.API.Entities.Post", "Post")
                        .WithMany("Votes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("LocalVibe.API.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
